In [ ]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/NagamallaVinay/Task-1/blob/main/Task_1.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**Task 1: Data Cleaning & Preprocessing**\n",
        "\n",
        "Objective:  Learn how to clean and prepare raw data for ML.\n",
        "\n",
        "Tools:  Python, Pandas, NumPy, Matplotlib/Seaborn\n",
        "\n",
        "---"
      ],
      "metadata": {
        "id": "82cWpnvk66QA"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**Importing Necessary Libraries**\n",
        "\n",
        "First, let's import all the libraries we will need for this task."
      ],
      "metadata": {
        "id": "IFPWfM888V2W"
      }
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Gv-DsGnU62zW",
        "outputId": "3dc282de-c9f5-4a64-c0e1-0b60ae2db93d"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Libraries imported successfully!\n"
          ]
        }
      ],
      "source": [
        "# Import libraries\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from sklearn.preprocessing import StandardScaler,LabelEncoder\n",
        "\n",
        "\n",
        "# Set plot style\n",
        "sns.set(style=\"whitegrid\")\n",
        "\n",
        "print(\"Libraries imported successfully!\")"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "## **Step 1: Import the Dataset and Explore Basic Info**\n",
        "We'll load the Titanic.csv dataset and perform an initial exploration."
      ],
      "metadata": {
        "id": "VsS7HzS28siz"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Load the dataset\n",
        "df = pd.read_csv('Titanic.csv')\n",
        "\n",
        "# Display basic info, stats, and null counts\n",
        "print(\"First 5 rows of the dataset:\")\n",
        "display(df.head())\n",
        "print(\"\\nDataset Information:\")\n",
        "df.info()\n",
        "print(\"\\nNull Values Count per Column:\")\n",
        "print(df.isnull().sum())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 941
        },
        "id": "brNmsFUY8xFW",
        "outputId": "9ea5e102-1c2f-41cd-a1a8-b1fb0d19e126"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "First 5 rows of the dataset:\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   PassengerId  Survived  Pclass  \\\n",
              "0            1         0       3   \n",
              "1            2         1       1   \n",
              "2            3         1       3   \n",
              "3            4         1       1   \n",
              "4            5         0       3   \n",
              "\n",
              "                                                Name     Sex   Age  SibSp  \\\n",
              "0                            Braund, Mr. Owen Harris    male  22.0      1   \n",
              "1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   \n",
              "2                             Heikkinen, Miss. Laina  female  26.0      0   \n",
              "3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   \n",
              "4                           Allen, Mr. William Henry    male  35.0      0   \n",
              "\n",
              "   Parch            Ticket     Fare Cabin Embarked  \n",
              "0      0         A/5 21171   7.2500   NaN        S  \n",
              "1      0          PC 17599  71.2833   C85        C  \n",
              "2      0  STON/O2. 3101282   7.9250   NaN        S  \n",
              "3      0            113803  53.1000  C123        S  \n",
              "4      0            373450   8.0500   NaN        S  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-4057c8d1-3ce3-4250-8dea-c166791a6371\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>PassengerId</th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Name</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Ticket</th>\n",
              "      <th>Fare</th>\n",
              "      <th>Cabin</th>\n",
              "      <th>Embarked</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>Braund, Mr. Owen Harris</td>\n",
              "      <td>male</td>\n",
              "      <td>22.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>A/5 21171</td>\n",
              "      <td>7.2500</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>Cumings, Mrs. John Bradley (Florence Briggs Th...</td>\n",
              "      <td>female</td>\n",
              "      <td>38.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>PC 17599</td>\n",
              "      <td>71.2833</td>\n",
              "      <td>C85</td>\n",
              "      <td>C</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>3</td>\n",
              "      <td>Heikkinen, Miss. Laina</td>\n",
              "      <td>female</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>STON/O2. 3101282</td>\n",
              "      <td>7.9250</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>Futrelle, Mrs. Jacques Heath (Lily May Peel)</td>\n",
              "      <td>female</td>\n",
              "      <td>35.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>113803</td>\n",
              "      <td>53.1000</td>\n",
              "      <td>C123</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>Allen, Mr. William Henry</td>\n",
              "      <td>male</td>\n",
              "      <td>35.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>373450</td>\n",
              "      <td>8.0500</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-4057c8d1-3ce3-4250-8dea-c166791a6371')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-4057c8d1-3ce3-4250-8dea-c166791a6371 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-4057c8d1-3ce3-4250-8dea-c166791a6371');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    <div id=\"df-b2e68ed1-29e5-4587-9f19-27caede2635e\">\n",
              "      <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-b2e68ed1-29e5-4587-9f19-27caede2635e')\"\n",
              "                title=\"Suggest charts\"\n",
              "                style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "      </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-b2e68ed1-29e5-4587-9f19-27caede2635e button');\n",
              "          quickchartButtonEl.style.display =\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"print(df\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"PassengerId\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 5,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          2,\n          5,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Survived\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Pclass\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 3,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Name\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Cumings, Mrs. John Bradley (Florence Briggs Thayer)\",\n          \"Allen, Mr. William Henry\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Sex\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"female\",\n          \"male\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 6.833739825307955,\n        \"min\": 22.0,\n        \"max\": 38.0,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          38.0,\n          35.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SibSp\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Parch\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Ticket\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"PC 17599\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Fare\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 30.5100288352535,\n        \"min\": 7.25,\n        \"max\": 71.2833,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          71.2833\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Cabin\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"C123\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Embarked\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"C\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Dataset Information:\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 891 entries, 0 to 890\n",
            "Data columns (total 12 columns):\n",
            " #   Column       Non-Null Count  Dtype  \n",
            "---  ------       --------------  -----  \n",
            " 0   PassengerId  891 non-null    int64  \n",
            " 1   Survived     891 non-null    int64  \n",
            " 2   Pclass       891 non-null    int64  \n",
            " 3   Name         891 non-null    object \n",
            " 4   Sex          891 non-null    object \n",
            " 5   Age          714 non-null    float64\n",
            " 6   SibSp        891 non-null    int64  \n",
            " 7   Parch        891 non-null    int64  \n",
            " 8   Ticket       891 non-null    object \n",
            " 9   Fare         891 non-null    float64\n",
            " 10  Cabin        204 non-null    object \n",
            " 11  Embarked     889 non-null    object \n",
            "dtypes: float64(2), int64(5), object(5)\n",
            "memory usage: 83.7+ KB\n",
            "\n",
            "Null Values Count per Column:\n",
            "PassengerId      0\n",
            "Survived         0\n",
            "Pclass           0\n",
            "Name             0\n",
            "Sex              0\n",
            "Age            177\n",
            "SibSp            0\n",
            "Parch            0\n",
            "Ticket           0\n",
            "Fare             0\n",
            "Cabin          687\n",
            "Embarked         2\n",
            "dtype: int64\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "  **Importing .csv file**"
      ],
      "metadata": {
        "id": "BXDKU6du85PW"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import files\n",
        "uploaded = files.upload()"
      ],
      "metadata": {
        "id": "UzYrJpmP89VF"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "# **Step 2: Handle Missing Values**\n",
        "We will impute missing values to create a complete dataset.\n",
        "\n",
        "Age: Impute with the median.\n",
        "\n",
        "Cabin: Drop the column due to too many missing values (>77%).\n",
        "\n",
        "Embarked: Impute with the mode."
      ],
      "metadata": {
        "id": "3m5RTuWS94MG"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Handle 'Age' - Impute with median\n",
        "median_age = df['Age'].median()\n",
        "df['Age'].fillna(median_age, inplace=True)\n",
        "print(f\"'Age' missing values filled with median: {median_age}\")\n",
        "\n",
        "# Handle 'Cabin' - Drop the column\n",
        "df.drop(columns=['Cabin'], axis=1, inplace=True)\n",
        "print(\"'Cabin' column dropped due to too many missing values.\")\n",
        "\n",
        "# Handle 'Embarked' - Impute with mode\n",
        "mode_embarked = df['Embarked'].mode()[0]\n",
        "df['Embarked'].fillna(mode_embarked, inplace=True)\n",
        "print(f\"'Embarked' missing values filled with mode: {mode_embarked}\")\n",
        "\n",
        "# Verify that there are no more missing values\n",
        "print(\"\\nNull Values Count After Imputation:\")\n",
        "print(df.isnull().sum())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "8KHWSg_P-I7w",
        "outputId": "a6cdb6cc-f3e7-49c1-bbe2-9ff29c4a1af6"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "'Age' missing values filled with median: 28.0\n",
            "'Cabin' column dropped due to too many missing values.\n",
            "'Embarked' missing values filled with mode: S\n",
            "\n",
            "Null Values Count After Imputation:\n",
            "PassengerId    0\n",
            "Survived       0\n",
            "Pclass         0\n",
            "Name           0\n",
            "Sex            0\n",
            "Age            0\n",
            "SibSp          0\n",
            "Parch          0\n",
            "Ticket         0\n",
            "Fare           0\n",
            "Embarked       0\n",
            "dtype: int64\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/tmp/ipython-input-5-2779151593.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
            "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
            "\n",
            "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
            "\n",
            "\n",
            "  df['Age'].fillna(median_age, inplace=True)\n",
            "/tmp/ipython-input-5-2779151593.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
            "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
            "\n",
            "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
            "\n",
            "\n",
            "  df['Embarked'].fillna(mode_embarked, inplace=True)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [],
      "metadata": {
        "id": "P5dBn2UsJmBf"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Drop irrelevant columns first as the data is Irrelevant and doesn't effect on Target\n",
        "cols_to_drop = ['PassengerId', 'Name', 'Ticket']\n",
        "cols_exist = [col for col in cols_to_drop if col in df.columns]\n",
        "if cols_exist:\n",
        "    df.drop(columns=cols_exist, inplace=True)\n",
        "    print(f\"Dropped {cols_exist} columns.\")\n",
        "\n",
        "# Convert 'Sex' and 'Embarked' using label encoding\n",
        "for col in ['Sex','Embarked']:\n",
        "    if col in df.columns:\n",
        "        le = LabelEncoder()\n",
        "        df[col] = le.fit_transform(df[col])\n",
        "\n",
        "df.head()\n",
        "\n",
        "print(\"\\nDataset after label encoding:\")\n",
        "display(df.head())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 261
        },
        "id": "rFy9pXqEHCvb",
        "outputId": "5e6467af-e88a-4f9b-e90b-6ca61477c843"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dropped ['PassengerId', 'Name', 'Ticket'] columns.\n",
            "\n",
            "Dataset after label encoding:\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked\n",
              "0         0       3    1  22.0      1      0   7.2500         2\n",
              "1         1       1    0  38.0      1      0  71.2833         0\n",
              "2         1       3    0  26.0      0      0   7.9250         2\n",
              "3         1       1    0  35.0      1      0  53.1000         2\n",
              "4         0       3    1  35.0      0      0   8.0500         2"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-b04408d7-9c68-4213-84cc-95e4db3355f8\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Fare</th>\n",
              "      <th>Embarked</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>22.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>7.2500</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>38.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>71.2833</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>7.9250</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>35.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>53.1000</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>35.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>8.0500</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-b04408d7-9c68-4213-84cc-95e4db3355f8')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-b04408d7-9c68-4213-84cc-95e4db3355f8 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-b04408d7-9c68-4213-84cc-95e4db3355f8');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    <div id=\"df-b48e766c-7684-42f8-ab98-892d1de94882\">\n",
              "      <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-b48e766c-7684-42f8-ab98-892d1de94882')\"\n",
              "                title=\"Suggest charts\"\n",
              "                style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "      </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-b48e766c-7684-42f8-ab98-892d1de94882 button');\n",
              "          quickchartButtonEl.style.display =\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"display(df\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"Survived\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Pclass\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 3,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Sex\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 6.833739825307955,\n        \"min\": 22.0,\n        \"max\": 38.0,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          38.0,\n          35.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SibSp\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Parch\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Fare\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 30.5100288352535,\n        \"min\": 7.25,\n        \"max\": 71.2833,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          71.2833\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Embarked\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 2,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Identify numerical columns to scale (excluding the target variable if it's numerical)\n",
        "numerical_cols = ['Age', 'Fare', 'Pclass']\n",
        "\n",
        "# Initialize the StandardScaler\n",
        "scaler = StandardScaler()\n",
        "\n",
        "# Apply standardization to the selected numerical columns\n",
        "df[numerical_cols] = scaler.fit_transform(df[numerical_cols])\n",
        "\n",
        "print(\"\\nDataset after standardization:\")\n",
        "display(df.head())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 243
        },
        "id": "xmhDU9zjNRiV",
        "outputId": "9808d584-50a5-4f90-ca90-c7868f49559f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Dataset after standardization:\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   Survived    Pclass  Sex       Age  SibSp  Parch      Fare  Embarked\n",
              "0         0  0.827377    1 -0.565736      1      0 -0.502445         2\n",
              "1         1 -1.566107    0  0.663861      1      0  0.786845         0\n",
              "2         1  0.827377    0 -0.258337      0      0 -0.488854         2\n",
              "3         1 -1.566107    0  0.433312      1      0  0.420730         2\n",
              "4         0  0.827377    1  0.433312      0      0 -0.486337         2"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-7c0968ee-8e25-4249-a379-62499cc270b6\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Fare</th>\n",
              "      <th>Embarked</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>0.827377</td>\n",
              "      <td>1</td>\n",
              "      <td>-0.565736</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.502445</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>-1.566107</td>\n",
              "      <td>0</td>\n",
              "      <td>0.663861</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0.786845</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1</td>\n",
              "      <td>0.827377</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.258337</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.488854</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1</td>\n",
              "      <td>-1.566107</td>\n",
              "      <td>0</td>\n",
              "      <td>0.433312</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0.420730</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>0</td>\n",
              "      <td>0.827377</td>\n",
              "      <td>1</td>\n",
              "      <td>0.433312</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.486337</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-7c0968ee-8e25-4249-a379-62499cc270b6')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-7c0968ee-8e25-4249-a379-62499cc270b6 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-7c0968ee-8e25-4249-a379-62499cc270b6');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    <div id=\"df-b1a90ada-d36f-4896-8e43-5fc93b6c4422\">\n",
              "      <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-b1a90ada-d36f-4896-8e43-5fc93b6c4422')\"\n",
              "                title=\"Suggest charts\"\n",
              "                style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "      </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-b1a90ada-d36f-4896-8e43-5fc93b6c4422 button');\n",
              "          quickchartButtonEl.style.display =\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"display(df\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"Survived\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Pclass\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.3109652708064075,\n        \"min\": -1.5661069258891576,\n        \"max\": 0.8273772438659699,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          -1.5661069258891576,\n          0.8273772438659699\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Sex\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.525171834873384,\n        \"min\": -0.5657364610748746,\n        \"max\": 0.6638610320657843,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          0.6638610320657843,\n          0.4333115021019107\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SibSp\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Parch\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Fare\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.6143098866514628,\n        \"min\": -0.5024451714361923,\n        \"max\": 0.7868452935884461,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          0.7868452935884461\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Embarked\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 2,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# **5.Visualize outliers using boxplots and remove them.**"
      ],
      "metadata": {
        "id": "cta79yGoOmVN"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Visualize outliers using boxplots\n",
        "plt.figure(figsize=(10, 5))\n",
        "\n",
        "plt.subplot(1, 2, 1)\n",
        "sns.boxplot(x=df['Age'])\n",
        "plt.title('Boxplot of Age')\n",
        "\n",
        "plt.subplot(1, 2, 2)\n",
        "sns.boxplot(x=df['Fare'])\n",
        "plt.title('Boxplot of Fare')\n",
        "\n",
        "plt.suptitle('Visualizing Outliers on Original Scale')\n",
        "plt.show()\n",
        "\n",
        "# Removing Outliers from 'Fare' using the IQR method ---\n",
        "print(f\"Shape of the dataframe before outlier removal: {df.shape}\")\n",
        "\n",
        "# Calculate IQR for 'Fare'\n",
        "Q1 = df['Fare'].quantile(0.25)\n",
        "Q3 = df['Fare'].quantile(0.75)\n",
        "IQR = Q3 - Q1\n",
        "\n",
        "# Define the upper bound for outlier detection\n",
        "upper_bound = Q3 + 1.5 * IQR\n",
        "print(f\"Outlier detection upper bound for Fare: {upper_bound:.2f}\")\n",
        "\n",
        "#Define the lower bound for outlier detection\n",
        "lower_bound = Q1 - 1.5*IQR\n",
        "print(f\"Outlier detection lower bound for Fare: {lower_bound:.2f}\")\n",
        "\n",
        "# Remove rows where 'Fare' is an outlier\n",
        "df_no_outliers = df[df['Fare'] <= upper_bound]\n",
        "\n",
        "# Remove rows where 'Fare' is an outlier\n",
        "df_no_outliers = df_no_outliers[df_no_outliers['Fare'] <= upper_bound]\n",
        "df_no_outliers = df_no_outliers[df_no_outliers['Fare'] >= lower_bound]\n",
        "\n",
        "print(f\"Shape of the dataframe after removing Fare outliers: {df_no_outliers.shape}\")\n",
        "\n",
        "\n",
        "# Removing Outliers from 'Age' using IQR method\n",
        "Q1 = df['Age'].quantile(0.25)\n",
        "Q3 = df['Age'].quantile(0.75)\n",
        "IQR = Q3 - Q1\n",
        "\n",
        "# Define the upper bound for outlier detection\n",
        "upper_bound = Q3 + 1.5 * IQR\n",
        "print(f\"Outlier detection upper bound for Age: {upper_bound:.2f}\")\n",
        "\n",
        "# Define the upper bound for outlier detection\n",
        "lower_bound = Q1 - 1.5*IQR\n",
        "print(f\"Outlier detection lower bound for Age: {lower_bound:.2f}\")\n",
        "\n",
        "# Remove rows where 'Age' is an outlier\n",
        "df_no_outliers = df_no_outliers[df_no_outliers['Age'] <= upper_bound]\n",
        "df_no_outliers = df_no_outliers[df_no_outliers['Age'] >= lower_bound]\n",
        "\n",
        "print(f\"Shape of the dataframe after removing Fare outliers: {df_no_outliers.shape}\")\n",
        "print(f\"{df.shape[0] - df_no_outliers.shape[0]} rows removed as outliers.\")\n",
        "\n",
        "# Update our main dataframe\n",
        "df = df_no_outliers"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 662
        },
        "id": "_AauUMBcOMrx",
        "outputId": "a9abfcc8-a692-4760-9ddc-0f66eadc192f"
      },
      "execution_count": 46,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 1000x500 with 2 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAxoAAAH6CAYAAACAmzr5AAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAATnRJREFUeJzt3Xd0FGXfxvErCQktBIgQelEwoUMACSXSpCNSpHfpSFFRNGBDBUSBB6mCgkj1AQXRgEhTaYGACIKUB6QXCVITCCkk8/7B2X1ZEiDlDpvA93MORzNtf3vv7MxcO3PPuFiWZQkAAAAADHJ1dgEAAAAAHj0EDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0gDfn5+albt27OLuO+Eqtx6tSp8vPzU2hoaIqWmdr5HxfdunWTn5+fw7DQ0FD5+flp6tSpTqoKNol9PinhzO9D/fr1Vb9+/Yf+uqZk9PqBx10mZxcApHevv/66Vq5cqffee09dunS577S9evXS1q1bNW3aNDVs2PAhVYjk2rdvnxYvXqwdO3bo33//VaZMmVSoUCEFBgaqZ8+eypcvn5HXCQoK0vfff68NGzaocOHCRpaJhMLCwjRv3jxt2bJFZ86c0a1bt5Q3b14988wz6ty5sypUqODsEjOU1atX67vvvtOBAwcUHh4uT09PPfHEEypTpoxq1aql1q1bO7tEABkEQQN4gPbt22vlypX67rvv7hs0zpw5o5CQEOXNm1f16tWTJP3000/KmjXrwyrVmC5duqhZs2YqWLCgU+ZPK5ZlacKECZo9e7YyZcqkmjVrqkmTJoqNjdXu3bv11Vdf6ZtvvtG4cePUpEkTp9RYoUIF/fTTT8qdO7dTXj+j+fnnnxUUFKSbN2+qfPnyatu2rdzd3fX3339r5cqV+v7779WnTx+98cYbcnFxSdayP/nkE928eTPVNabX70Ni3n33XS1dulRZsmRRnTp1VLhwYVmWpePHj+vXX3/Vjh07CBoAkoygATxAQECAihcvrgMHDmj//v0qW7ZsotN99913sixLL774ojJluv3VKlGixMMs1Rhvb295e3s7bf60Mn36dM2ePVuFChXSrFmz9PTTTzuMX7NmjYYPH65hw4YpV65cql69+kOvMWvWrBl2vXnYtm3bpmHDhilTpkyaPHlygnB45MgR9e/fX7Nnz1a2bNk0aNCgZC3fVDBIr9+Hu/3+++9aunSp8ufPryVLlih//vwO42NjY7Vjxw4nVQcgI6KPBpAE7du3lyQtXbo00fFxcXFavny5XFxc1LZtW/vwxPo/XL9+XdOnT9fzzz+vypUry9/fXw0aNNCrr76qv/76yz7dg67VT+za5YiICM2ePVvdu3dX7dq1Va5cOVWvXl0DBgzQ7t27k/x+E7um3Ha9+r3+3fk+73VNum26y5cv691331VgYKDKlSun5s2ba9myZYnWEhMTo6lTp+q5555TuXLlVL9+fU2aNEkxMTHJ6gNz5swZff7553J3d9fnn3+eIGRIUuPGjTVixAjFxcVp1KhRio+Pf+B7si3bz89PQUFBDu/1+++/lyQ999xz9nZ60PXm9/vcr169qokTJ6pp06aqUKGCqlSpoh49emjLli0Jpl2+fLn8/Py0fPlybdq0Sd26dVOVKlUc+hz8/vvvGjBggH1dqVWrltq3b69p06bdt8Y7xcfH65tvvtGLL74of39/VapUSS+++KIWL17s0H53tkty14F7ve6oUaMUFxenkSNHJnoG6umnn7Z/5jNmzNDZs2ft4+78zI4fP65XX31VNWrUUKlSpeyf8b36aCR3nTT1fYiJidHChQvVt29f1atXT+XKlVO1atXUs2dPbdy4Mcltdy+2bUSjRo0ShAxJcnd3V61atRKdd8uWLRowYIBq1KihcuXKqU6dOho4cKBCQkLSrP6VK1eqW7duqlq1qsqXL6+mTZtqxowZiomJSfayAKQNzmgASdC6dWtNmjRJq1atUlBQUILLoTZt2qSwsDDVqlVLRYoUuedyLMtSnz59tHv3bvn7+6tdu3Zyc3NTWFiYQkNDVbVqVZUrVy7FdR49elSfffaZqlatqrp168rLy0v//POPfvnlF23evFmff/65ateunaJlt27dWtWqVUsw/Pfff9f27duVJUuWJC0nPDxcnTp1koeHhxo3bqyYmBj9/PPPGjlypFxdXR0uy7AsS0OGDNFvv/2m4sWLq2vXrrp165a+//57/f3338mqf/ny5bp165aaNm163w6+7dq10/Tp03X8+HHt2LEjxWc1Bg8erPXr1+vQoUPq3r27vLy8JEk5cuRI0fLOnj2rbt266ezZs6pataqeffZZ3bx5U7/++qv69OmjDz/80B6I77RmzRpt3rxZtWvXVseOHXXu3DlJt9fZ/v37y9PTU/Xr11e+fPl09epVHTt2TIsXL9bgwYOTVNfw4cO1cuVKFShQQG3btpWLi4vWr1+vDz74QLt27dLEiRMTzJOcdeBeduzYoRMnTsjHx0ft2rW753R+fn567rnn9PPPP2vZsmUaOnSow/hTp06pffv2Kl68uFq0aKGoqCh5enrec3km10kpeW1x7do1jRkzRv7+/qpZs6a8vb3177//6tdff1W/fv00evTo+7bFg+TKlUuSdPLkyWTNN2XKFE2fPl3ZsmVTgwYNVKBAAV24cEG7d+/Wjz/+qJo1axqvf8SIEVq+fLny58+vRo0aycvLS3v27NHkyZO1bds2zZ07135mGYDz8C0EksDb21sNGjTQ6tWrtXr1arVp08ZhvO1MR2IHenc6fPiwdu/erQYNGmj69OkO4+Lj4xUREZGqOkuUKKFNmzYluEzj/Pnzatu2rT7++OMUB42737MkHTp0SHPnzlXu3Ln17rvvJmk5hw4dUtu2bfXhhx/Kzc1NktSjRw+98MIL+vLLLx0OrH744Qf99ttvqlq1qubOnSsPDw9J0tChQx/Y1nfbtWuXJNkPeu4lU6ZMCggI0MqVK/XHH3+kOGgMGTJEZ8+e1aFDh9SjR49UdwYPCgrSuXPn9J///EfNmze3Dw8PD1e3bt00evRo1a9fX3ny5HGYb+PGjfriiy8SfO7ffvut4uPjtWDBApUqVcph3OXLl5NU08qVK7Vy5UqVKVNGCxcuVPbs2SVJr776qrp27aqVK1eqbt26atGihcN8yVkH7sX2eVarVs2+jHupVauWfv75Z/3xxx+JLqd///4aNmxYkt6zyXVSSl5b5MyZU7/++muCsw0RERHq1KmTxo8frxYtWiQ59N+tdu3aypEjhzZu3KgBAwaoefPmKl++vIoVK3bP/i1btmzR9OnTVbhwYS1evDjBjRTOnz9vvP7ly5dr+fLlatiwoSZMmOAw/dSpUzVt2jQtWrRIPXr0SG4TADCMS6eAJOrQoYOk2wdod7pw4YI2bdqkJ554Qs8991ySlpXYjtTV1VU5c+ZMVY05cuRI9Frw/Pnzq0mTJjp27Jj9F+3UCgsLU//+/XXr1i3NmDFDRYsWTdJ8WbNm1YgRIxwODkuWLKnKlSvr6NGjunHjhn34ihUrJN0+cLUd0EmSl5eXXn755WTV+++//0pSopeE3K1AgQKSbn+26cGhQ4e0Y8cONWrUyCFkSLfbYsiQIYqOjtaaNWsSzPvcc8/dN1xmzpw5wbCk9iewXd7z+uuv20OGJGXLlk3Dhw+XlPD7IiVvHbgX2+dp+6zux/aZJ/Z55smTJ8lnbySz66SUvLbw8PBIdP3NkSOHXnzxRV27dk379u1Ldg02+fLl07Rp01S0aFH9+uuveuONN9S4cWNVqVJFvXv31g8//KC4uDiHeRYuXCjpdhBO7G5td9Zrqv758+crU6ZMGjt2bIJt6csvv6xcuXIpODg4Se8ZQNrijAaQRNWrV1fRokX1xx9/6OjRo/YOu7ZLclq3bi13d/f7LqNkyZIqXbq0Vq5cqbNnz+q5555TlSpVVK5cOYeDltTYtWuX5s+frz179ujSpUuKjY11GB8WFpbqTq43btzQgAEDFBYWpv/85z+qXLlykuctVqxYopem2A5AwsPD7QetBw8elKurq/z9/RNMX6VKlRRWn/HYrp2/fv16on03bGcgjh07lmDcvW7t2qJFC61du1bt27dX06ZNVb16dVWuXDlJQczmwIEDcnV1TfSSumeeeUZubm46ePBggnHJWQfSWqlSpZL13TO9Tia3LY4cOaI5c+Zo586d+vfffxUdHe0wX1hYWLJruFP16tW1Zs0a/fHHH9qxY4cOHjyoP/74Q1u2bNGWLVu0YsUKzZo1y95me/bskYuLi5599tkkLT+19d+8eVOHDh1S7ty5NW/evESn8fDw0NGjR5NUD4C0RdAAksjFxUXt2rXTxIkT9e233yooKEiWZem7776Ti4tLki6bcHNz07x58zR9+nStWbNGEyZMkCRlz55drVu31rBhw1J1gLVu3ToNHTpUmTNnVs2aNVW0aFFlzZpVrq6u2rFjh3bs2JHqjpJxcXF67bXXdODAAb3++utq1qxZsua39VW4m+166jt/MY2IiFDOnDkTvdb67kuEHiRPnjw6evSow6Uc9/LPP/9Iknx8fJL1Gmnl6tWrkqStW7dq69at95wuMjIywbB7tVOjRo00a9YsffXVV1q+fLmWLFkiSSpbtqxef/31e3b6vZPt80nsQD1TpkzKnTu3Ll26lGBcctaBe7G9L9tndT+2zzyxzzO565HJdVJKXlvs2bNHPXr0UFxcnKpXr6769evL09NTrq6uOnjwoDZs2GCkI7Srq6uqVq2qqlWrSrrdL2Xr1q0KCgpSSEiIFi9erJ49e0r6//ZIyuVaJuoPDw+XZVm6fPlysm5aAMA5CBpAMrRp00ZTpkzRihUrNGzYMO3atUunT59W9erVVaxYsSQtI2fOnBo5cqRGjhypkydPaseOHVqyZIkWLlyo8PBwjR8/XtLtnb0k3bp1K9HlhIeHJzhImTx5stzd3bVs2bIEt0h97733jNya8qOPPtLGjRvVvn179evXL9XLux9PT09du3ZNt27dSnBgd/HixWQtq0qVKgoNDVVISMh9Q2FcXJy9ne48U2O7Rj2xg+DU9q15EFsH8rffflvdu3dP1rz3e3ZE3bp1VbduXUVGRurPP//Ub7/9pm+++Ub9+/fXihUrVLJkyQfWde3aNcXGxiY4m3fr1i1duXLlvh2rU8N29mDHjh2Ki4u7bz8N252PEjvzltxna5hcJ5Pr888/V1RUlObPn6+AgACHcbNmzdKGDRvS5HVdXFwUGBioV155Re+88462b99uDxo5cuTQ1atXFRUV9cCwYaJ+2/pUpkwZ+13dAKRf9NEAkiFPnjyqX7++rly5ovXr19uvP7f130iuYsWKqV27dlq4cKGyZcvmsKO1hYjEfoE/efJkoge3J0+eVMmSJROEjPj4eHvn2dSwPdAuMDBQ77//fqqX9yClS5dWfHx8orfmTe77adOmjdzc3LR+/XodOXLkntMtW7ZMFy5c0JNPPulwSZCt/0xiv6DfeVviO9nCYmK3eU2OihUrSrp9h6+0kC1bNtWoUUMjRoxQ//79FRsbq02bNj1wPtvnk1hdO3fuVFxcnMqUKZMWJatatWoqVqyYLly4cN/b4h45ckTr169XpkyZ9OKLL6b6dU2uk8l18uRJ5cqVK8FBuqSH8nyLxM62VqpUSZZlafPmzQ+c30T92bNn19NPP60jR47Yz/QBSL8IGkAy2W6/OHfuXK1bt065c+dWgwYNkjTv6dOndfr06QTDbb8K3/mL4FNPPSVPT09t2LDB4fKTqKgojR49OtHlFypUSCdOnHC4ztmyLE2dOjVFt96809q1azV+/Hj5+vpq8uTJD+XWka1atZIkffbZZw6XVERERGjGjBnJWlaRIkXsB9EDBw5MtD3Wr1+vMWPGyM3NTaNGjbIHBen/+zrY+uTY/PPPPwnuIGZju11oajvgly9fXlWrVtW6dev03XffJTrN//73v0QvU7qXnTt3Jnq2zLaMpFwKYztwnzhxosMTtG/evGm/re2dz5Uxyc3NTe+//75cXV01ZswYrVu3LsE0R48e1cCBA+2feaFChVL9uibXyeQqVKiQrl69qkOHDjkM//bbbxN9lkpybdq0SWvXrk3Qr0u63S9r/vz5kmS/pEqSunbtKkkaN25cov0r7hxmqv6ePXsqNjZWI0eOVHh4eILx165d0/79+5O8PABph0ungGQKDAxUoUKFtHfvXkm3d7RJ7Uz6v//9T4MHD1b58uVVokQJ+fj46PLly9qwYYNiY2PVt29f+7Tu7u7q3r27ZsyYoVatWqlhw4a6deuWQkJC5OPjk+j15j179tT777+v1q1bq1GjRsqUKZO983q9evX066+/pvh9Dx8+XPHx8Spfvrzmzp2bYHyhQoUSvQVuarRq1UqrVq3S5s2b1aJFC9WvX1+xsbFau3atypcvr+PHjyfr0pchQ4bo5s2bmjt3rlq2bKnAwECVLFlSt27d0u7du/Xnn38qS5YsmjhxYoLb2lasWFHPPPOMdu7cqXbt2ql69eq6ePGifv31VwUGBiZ6pqNGjRqaM2eO3n33XTVq1EjZs2eXl5eX/eAsOSZOnKgePXro7bff1oIFC1SxYkXlyJFD58+f1+HDh3X48GEtWbJETzzxRJKWN3r0aIWFhaly5coqVKiQ3N3dtX//fm3fvl2FChVKcHerxLRo0UIbNmzQ6tWr1bx5czVo0MD+HI0zZ86oWbNmeuGFF5L9XpOqVq1amjBhgkaOHKnBgwerQoUKqly5stzd3fX3339ry5Ytio2NVe/evZP9VPB7Mb1OJoft4YydO3dW06ZNlSNHDv3111/atWuXGjdunOhdx5Lj2LFj+vjjj5UzZ05VqVJFxYsXl5ubm86fP6+NGzcqPDxcFStWdFh/AwMDNXDgQH3++edq2rSp/TkaFy9e1K5du1SpUiWNGzfOaP1t27bV/v37tXjxYjVs2FCBgYEqUKCArl27pjNnzmjnzp1q06aNPvzww1S1B4DUI2gAyWTrFP7ZZ59JUrIekFWuXDn169dPO3bs0ObNm3Xt2jV5e3urbNmy6tatm+rUqeMw/dChQ5U1a1YtXbpUS5cuVZ48edSsWTMNGTIk0QPBjh07ysPDQ/PmzdOKFSuUOXNmVa1aVR9//LHWrl2bqqARFRUlSfe8TKVatWrGg4aLi4umT5+umTNn6ocfftCCBQvk4+Oj1q1bq3Pnzlq/fn2y+gC4uroqKChIzZo106JFi7Rz505t27ZNbm5uKlSokHr16qUePXrc885LM2bM0KeffqoNGzZowYIFKl68uIYPH65atWpp9erVCaZ/9tlnFRQUpKVLl2revHmKjY1VoUKFUhQ08ufPr2XLlmnhwoVau3atgoODFRcXpzx58qhkyZLq2rWrfH19k7y8/v37a/369frrr7+0bds2ubi4qGDBghowYIB69OiR5Fst/+c//9EzzzyjZcuW2TuUlyhRQr169VKnTp2S/T6Tq3nz5qpSpYrmzZunLVu2aOnSpbp165by5s2r5s2bq0uXLve881ZKmF4nk6N27dqaOXOmPv/8c/30009yc3NThQoVNH/+fJ0+fTrVQeOFF16Qp6enQkJCdOjQIf3++++KjIxUjhw5VKpUKTVp0kTt2rVL8MPKq6++Kn9/f82fP1+//fabIiMj9cQTT6hcuXJq2bJlmtT//vvvq3bt2vrvf/+rkJAQe6f0AgUKqHfv3mkacAEknYtlWZaziwCA5Nq6dat69eqlfv366fXXX3d2OQDrJADchT4aANK1xK77vnLlir0PQMOGDR92SXjMsU4CQNJw6RSAdG3cuHE6dOiQ/P395e3trfPnz2vz5s26evWqOnToYPSyGCApWCcBIGkIGgDStYYNG9o7XUdERMjDw0NPP/202rZtm2Z3NALuh3USAJKGPhoAAAAAjKOPBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggbSPT8/P02dOtXZZTjYu3evOnbsqEqVKsnPz08HDx50dkkAgIeAfRKQdJmcXQCcZ/ny5RoxYoTDMG9vb5UsWVJ9+vRRnTp1nFSZGX///bdWr16t1q1bq3DhwsaWGxsbq1dffVUeHh4aMWKEsmTJooIFCz5wvo0bN6pfv37KmzevNm3aJFdXcj4A2LBPSpnk7JNCQ0PVvXv3RMc1a9ZMkyZNMlYXIBE0IGno0KEqXLiwLMvSpUuX9P3336tfv36aOXOm6tWr5+zyUuzvv//WtGnTVK1aNaMb9VOnTuns2bMaPXq02rVrl+T5fvzxRxUqVEhnz57V9u3bVbNmTWM1AcCjgn1S8qRkn9StWzeVL1/eYVihQoWM1QTYEDSg2rVrO2xw2rZtq1q1amnlypUZeqOeVi5fvixJypEjR5LniYyM1C+//KJhw4Zp+fLlCg4OJmgAQCLYJyVPSvZJVatWVZMmTYzWER0dLXd3d87WwwFrAxLw8vJS5syZlSmTYw6NjIzUuHHjVKdOHZUrV06NGzfWnDlzZFmWJCkqKkpNmjRRkyZNFBUVZZ/v6tWrCgwMVMeOHRUXFydJCgoKkr+/v06fPq3evXurUqVKCgwM1LRp0+zLu58DBw6oT58+qly5svz9/dWjRw/t2bPHPn758uV65ZVXJEndu3eXn5+f/Pz8FBoaet/lbtu2TZ07d1alSpVUtWpVDRw4UEePHrWPDwoKUteuXSVJr7zyivz8/NStW7cH1rtu3Tp7+zRr1kxr165VdHR0gumioqI0evRoBQQEyN/fXwMGDFBYWFii1wSHhYVpxIgRqlmzpsqVK6fmzZvru+++e2AtAJCRsE8yv0+6l6tXr+qTTz5RixYt5O/vr8qVK6tPnz46dOiQw3ShoaHy8/PTqlWrNGnSJD377LOqWLGirl+/Lkn6888/1bt3b1WpUkUVK1ZU165dtWvXrhTXhYyLMxrQ9evX7b+IXLp0SQsWLFBkZKReeOEF+zSWZWngwIEKDQ1V27ZtVbp0aW3evFmffvqpwsLCNHLkSGXJkkWffPKJOnXqpEmTJtmvtf3www8VERGhjz/+WG5ubvZlxsXFqU+fPqpYsaKGDx+uzZs3a+rUqYqLi7NvkBNz5MgRdenSRdmzZ1efPn2UKVMmLVmyRN26ddPChQtVsWJFPfPMM+rWrZsWLFigAQMG6KmnnpIklShR4p7LDQkJUd++fVW4cGENHjxYUVFRWrhwoTp16qTly5ercOHC6tChg/Lly6eZM2faTz3nyZPngW0cHBysgIAA5c2bV82bN9fEiRP1yy+/qGnTpg7TBQUFafXq1WrZsqUqVqyonTt3ql+/fgmWd/HiRbVv314uLi7q0qWLvL29tWnTJr399tu6fv26evbs+cCaACA9Yp90W1ruk27cuGFvY5tcuXLp9OnTWr9+vZo0aaLChQvr4sWLWrJkibp27apVq1YpX758DvPMmDFD7u7u6t27t2JiYuTu7q5t27apb9++KleunAYPHiwXFxctX75cPXr00OLFi1WhQoUH1odHiIXH1rJlyyxfX98E/8qVK2ctX77cYdp169ZZvr6+1owZMxyGDxkyxPLz87NOnjxpHzZx4kSrVKlS1s6dO63Vq1dbvr6+1tdff+0w31tvvWX5+vpaH330kX1YfHy81a9fP6ts2bLWpUuX7MN9fX2tKVOm2P9++eWXrbJly1qnTp2yDwsLC7P8/f2tLl262IfZXnv79u1Jao+WLVtaNWrUsK5cuWIfdvDgQatUqVLWm2++aR+2fft2y9fX11q9enWSlnvx4kWrTJky1tKlS+3DOnToYA0cONBhur/++svy9fW1xowZ4zA8KCgoQRuMHDnSqlWrlnX58mWHaV977TWrSpUq1s2bN5NUGwCkF+yTHKXFPsk2bWL/Tp8+bUVHR1txcXEO85w+fdoqV66cNW3atATLee655xz2N/Hx8VajRo2sXr16WfHx8fbhN2/etOrXr2+99NJLSXrveHRw6RT03nvvae7cuZo7d67Gjx+vgIAAvfPOO1q7dq19mk2bNsnNzS3BKdlevXrJsixt2rTJPmzw4MEqWbKk3nrrLX3wwQeqVq3aPe9y0aVLF/v/236dj42N1bZt2xKdPi4uTlu3blWDBg1UpEgR+3AfHx89//zz2rVrl/3UbXJcuHBBBw8eVOvWrZUrVy778FKlSqlmzZrauHFjspdps2rVKrm4uKhRo0b2Yc8//7w2bdqka9eu2Ydt3rxZktS5c2eH+W2nxW0sy9LatWtVv359WZaly5cv2/8FBgYqIiJC+/fvT3G9AOBM7JPSdp8kSYMGDbK3se1f3rx55eHhYe9jERcXpytXrihbtmx68skndeDAgQTLadWqlbJkyWL/++DBgzpx4oRatGihK1eu2PdNkZGRqlGjhnbu3Kn4+PhU1Y6MhUunoAoVKjh0vHv++efVqlUrffjhh6pbt648PDx09uxZ+fj4yNPT02Fe22nfs2fP2od5eHho7Nixatu2rTJnzqyxY8fKxcUlweu6uro6bJgl6cknn0ywvDtdvnxZN2/etE93dy3x8fH6559/9PTTTyfx3d927tw5h9e/e7lbtmxRZGSksmXLlqzlSrfvNlWhQgVdvXpVV69elSSVLl1asbGx+vnnn9WhQwd7Da6urgnuRlKsWDGHvy9fvqzw8HAtWbJES5YsSfQ17z4lDgAZBfuktN0nSZKvr2+iNySJj4/X/PnztXjxYp05c8beh0WSQ+CxuXt/deLECUnSW2+9dc/XjoiIUM6cOVNUNzIeggYScHV1VUBAgObPn6+TJ08mewMpSVu2bJF0+y4UJ0+eTLDxflycOHFC+/btkySHMxo2wcHB9qCRVLZfg1544QW1bt060Wn8/PySWSkApE/skx6emTNnavLkyXrxxRf1yiuvKGfOnHJ1ddXYsWMT7RR/59kMSfZp3nzzTZUuXTrR10hpOELGRNBAomy/YkRGRkq6fX/tbdu26fr16w6/IB07dsw+3ubQoUOaPn262rRpo0OHDumdd95RcHBwglvvxcfH6/Tp0w6/2Bw/fjzB8u7k7e2trFmz2qe707Fjx+Tq6qoCBQpIUqK/WN2L7eFG91pu7ty5U7RxDA4Olru7uz799NMEt/zbtWuXFixYoHPnzqlgwYIqWLCg4uPjdebMGRUvXtw+3cmTJx3m8/b2Vvbs2RUfH88tcgE8FtgnOS43pfukB1mzZo0CAgI0duxYh+Hh4eHKnTv3A+e3BThPT0/2T5DE7W2RiNjYWG3dulXu7u7209C1a9dWXFycFi1a5DDt119/LRcXF9WuXds+74gRI+Tj46O3335bH3/8sS5evJhgo2Vz5/Isy9KiRYvk7u6uGjVqJDq9m5ubatWqpQ0bNujMmTP24RcvXtTKlStVpUoV+04na9askm6fpn0QHx8flS5dWitWrFB4eLh9+OHDh7V169YUP5E2ODhYVapUUbNmzey3WbT969OnjyRp5cqVkqTAwEBJ0uLFix2WsXDhQoe/3dzc1LhxY61Zs0aHDx9O8JpcNgXgUcI+ydw+6UHc3NwSnLlYvXq1wsLCkjR/uXLlVLRoUX311Ve6ceNGgvHsnx4/nNGANm3aZP8V6PLlywoODtaJEyfUr18/+wayfv36CggI0KRJk3T27Fn5+flp69at2rBhg3r06KGiRYtKkj7//HMdPHhQX3/9tTw9PVWqVCkNGjRIn332mZo0aeKwccycObM2b96st956SxUqVNDmzZv122+/acCAAfL29r5nva+++qpCQkLUuXNnde7cWW5ublqyZIliYmI0fPhw+3SlS5eWm5ubvvzyS0VERMjDw0PVq1fXE088kehy33zzTfXt21cdOnRQ27Zt7bcSzJEjhwYPHpzsdv3zzz918uRJh86Fd8qXL5/KlCmj4OBg9evXz34f+Hnz5unq1av229varnm989ew119/XaGhoWrfvr3atWunkiVL6tq1a9q/f7+2bdumHTt2JLteAEgP2CfdZnqflBR169bV9OnTNWLECPn7++vw4cMKDg5O8qVmrq6uGj16tPr27avnn39ebdq0Ub58+RQWFqbQ0FB5enpq5syZaVI70imn3e8KTpfYrQTLly9vtWzZ0lq8eLHDreksy7KuX79ujR071goMDLTKli1rNWrUyJo9e7Z9ur/++ssqU6aMw+0BLcuybt26Zb344otWYGCgde3aNcuybt9KsFKlStapU6esXr16WRUrVrRq1qxpTZkyJcGt9e6+laBlWdb+/futXr16WZUqVbIqVqxodevWzfrjjz8SvMelS5dazz33nFW6dOkk3VYwJCTE6tixo1WhQgWrcuXKVv/+/a2///7bYZqk3krwo48+snx9fR1ueXi3qVOnWr6+vtbBgwcty7KsyMhI64MPPrCqVatmVapUyXr55ZetY8eOWb6+vtasWbMc5r148aL1wQcfWHXq1LHKli1r1apVy+rRo4e1ZMmS+9YFAOkR+6SETO6TkjJtdHS0NW7cOKtWrVpWhQoVrI4dO1q7d++2unbtanXt2jXJyzlw4IA1ePBgq1q1ala5cuWsevXqWa+88ooVEhLywBrxaHGxrCQ88hIwLCgoSGvWrNHu3budXUq6d/DgQbVq1Urjx493eGAVAMAM9klA2qCPBpCOREVFJRg2b948ubq66plnnnFCRQAAAClDHw0gHZk9e7b++usvVa9eXW5ubtq0aZM2bdqkDh062O9cAgAAkBEQNIB0xN/fX1u3btWMGTMUGRmpAgUKaMiQIRowYICzSwMAAEgW+mgAAAAAMI4+GgAAAACMS9KlU7t375ZlWXJ3d0/regAAd4iNjZWLi4v8/f2dXUq6w74JAJwjqfumJJ3RsCwrwZMinc2yLMXExKS7uh5FtPXDQ1s/XBmhvdPj9je9SC9tkxHWo/SCtko62irpaKukM9VWSd3+JumMhu3XovLly6eqKJMiIyN18OBBlSxZUtmyZXN2OY802vrhoa0frozQ3vv27XN2CelWetk3ZYT1KL2grZKOtko62irpTLVVUvdN9NEAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYl8nZBQBJdeHCBYWHhzu7jDQVFRWlc+fOKXPmzMqSJYt9uJeXl3x8fJxYGYCMLj1sQ++1jXvcsE3H44KggQzhwoULGjBwoGJjYpxdilO4e3ho5uefs2MCkCKP+zY0vWGbjscFQQMZQnh4uGJjYpSlYHW5eng5u5wUiY8OV9Q/25WlQHW5Zk76e4iPCVfUue0KDw9npwQgRUxvQ1O6PQPbdDxeCBrIUFw9vOSW1dvZZaSKa+aM/x4AZEymt6FszwDcD53BAQAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0EiFa9euObsEAIbxvX688HkDyIgyyraLoJFC58+fV/fu3XX+/HlnlwLAEL7Xjxc+bwAZUUbadhE0Uuj69euKj4/X9evXnV0KAEP4Xj9e+LwBZEQZadtF0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxmdL6BeLi4nTgwAGdP39e27Zt06lTp3Tp0iW5uLgoX758GjdunHLmzClJ+vfffzVkyBBFRUUpS5Ysmjp1qvLmzStJunbtmkaOHKkrV64od+7cev/99+2vcb/5bty4oUmTJun8+fPKnz+/XnvtNWXPnl2SdPPmTX399dc6d+6cChYsqJ49eypr1qwPHAfg8XLlyhW98cYbCg8Pl5eXlyZMmKDcuXNLksLCwjR48GBFR0crc+bM+uyzz/T777/rn3/+Ub58+VSsWDFFRETI29tbZcqUkZubm5PfDQDgcZDYsawkxcfHa//+/YqMjEzzfVOaBo2QkBDNmTNHFy5cSHT8mTNn1LVrV+XKlUvXr1/XrVu37ONu3LihXr16KVOmTPL09NTVq1ft4yIiItS7d29lz55d0dHR95zvySef1JEjR+zjTp48qY4dO+rpp5+Wt7e3QkND7eP27Nmjn376SQEBAZJ0z3HvvPNOqtsFQMbRoUMHRUZG2v+OiopS9+7dlS1bNkVFRSk+Pt5h3IABA+65LB8fH/Xu3Vs1a9ZM05oBAI+30aNHJ3osW6JECV26dMnhuDot901pdulUSEiIxo0bp5iYmAdOe/XqVXtYyJ07t1577TX7r4W3bt2yN4afn59Gjx4tPz8/SbdDxf3mO3LkiFxcXFSvXj1NmTJF9erVk4uLi44cOaLQ0FBlypRJbdu21RdffKG2bdsqU6ZMCg0Nve+40aNHm24qAOnUnSGjaNGievfdd1W0aFFJUmRkpD1k5MiRQ5UqVUowf/HixeXp6SlJqlu3rooXL65x48YpJCTk4bwBAMBjxxYy7j6WdXNz09GjRxUbG6uPPvpIS5cu1fjx49N035QmZzTi4uI0Z84cVa5cWbt27XIYt2jRIk2ePFknTpzQxYsXHX4NnDZtmooVKyZJql+/vk6ePKnBgwdLkqZMmaInn3xSklSxYkUdOnRIw4cPT3S+s2fP2n9VnD59uooUKSJJGjZsmHr37q2uXbtKkr766it7MOnRo4datWplHzd//nzlyJHDPq5Tp07q0KGDQkNDdfPmTcMtBiC9uXLlij1kLFq0SF5eXpKkatWq6ciRIxo2bJgk6bPPPlORIkXUrl075cqVS5988on69+8vSRo5cqTy5s2rl156SZs3b9Z///tfjR8/Xl999ZUCAgK4jAoAYNTNmzftIWPJkiXy8PCQJHXt2lW//fabLl26pBs3bqh48eLKmjWrSpUqpbfffltjxoxJk31TmgSNAwcO6MKFCypRooTDcD8/P3l5ealdu3YaPny4ateurU2bNtnHf/rpp5o+fbrD3zYjRozQf//7X/vfd/bRuHu+uXPn2v9/+PDhDvMtXrzY/v/Tp093uBTqznELFy7UwIED7X97eHioZcuWWrZsmb7++ms1bNhQknT69OkHNUeGFxUVpXPnzilz5szKkiWLU2p4HNr5QWgD8+5et+9s4zfeeEPS7TMZtpBhM3LkSPv/jx07Vi+88ILi4+PVtWtXXbp0yT5u6NCh+vbbb9WlSxdNnz5da9assW//Dhw4oPLly6fxO0RSpPa7lR62kQ/C9iP9edBnkhHWq/TicWur+607X3/9tSSpVatW9pAh3T42v3jxop599llt3rxZCxYs0JAhQyRJrq6uabZvSpOgcfnyZUnS9evXHYZ369ZNkuyXHpQsWdIhaFy5csVh+jv/joqKchh35993z3f+/Pl7znfu3LlEp7t73J3/b9OgQQMtW7bMYdx//vOfBNMBaYF17eEKDw+XdPuM5t2io6Mdpvvnn38k3T7bsXfv3gTTPfPMM5Kkf/75x/4jhW07CefjuwVnYL1DWrAdozZq1MhhuG2f07x5c23evDnBMbDt2Nz0vilNgoa3t7ck2a9NtlmwYIEqVqyoU6dOSZL+/vtvh/G2y5ju/DsiIkKSEiTULFmy2C9ruHu+/Pnz6+TJk4nOV7BgQe3Zs8c+3b3GFSxYMMH7Wr9+fYJxw4YNs1+a9aiKiorS8ePH9eSTTzr1jMbjvlF+HNa1h+3udfvO9czLy0tRUVGaN2+eqlWr5jBf5syZ7T9ieHl5qUCBApKkHTt2OGwfMmfOLEnauXOnJKlAgQL27Z9tOwnnS+13Kz1sIx+EbWj686D1LiOsV+nF49ZW9/s+245l165d6/BDmW2fs2rVKkkJj4HTat+UJkGjTJky8vHxSdAR/H//+5/Cw8P17bffysfHR1u2bHEY/+abbyb429ZH4+OPP3YY98EHH9j7aNw930svvWTvaT9+/HiHcZ07d9ZPP/0kSRo0aNA9x9n6atjExMTohx9+kCT17NlTZ8+elSQVKVJEJUuWTLQdHhWRkZGKjo7WU089pWzZsjm7nMfW47CuPWz3W7cnTJig7t2769SpU/bb2tqMHTvW3kdj5MiRKlKkiL766istXLhQn3zyiX26KVOm6NatW1q0aJHc3NzUuHFjjR8/Xvny5VOZMmUezpvEA6X2u8U2EinxoPWO9SrpaKv/17NnT/30009asWKFOnXqZL98qkyZMsqTJ4/92Nt2lZF0+3a33377bZrsm9IkaLi5ual3794aN26ccuXK5XALrS5dutxzvsGDByt37tzq0qWLFi1a5HBJ1NChQ+Xr66vOnTtr8eLFOnz4cJLmGzRokOrUqaOWLVvqhx9+0MaNG+3jevXqpZYtW6pBgwZav369PUhIUvfu3ROMu3XrlgICAnieBvAYyJ07t7Jly6bIyEh16dJFRYoUUdeuXbVw4UKH62NfffVV5ciRQ2XLltW+ffvsHcGl24Hk4sWLun79uurUqaPx48dr586dCgoKoiM4AMC4rFmzKiAgQKGhoerQoYPDseyVK1dkWZayZ8+uEydOyNfXV6dOndK3336bZvumNHuORs2aNRUUFKQ5c+Y8cNo7n6Nx5coVTZs27f8LvOM5GocPH9aoUaPs4+58jkZi89meo/Hbb7/pt99+s4+78zkay5Yt07Jly+zj7nyORmLjeI4G8PhYsmSJ/Ra3p0+fdjizeudzNCIiIrRv374E8584ccL+/xs3blS+fPkUFBTEczQAAGnmnXfesd/i9u5jWdtzNN599137sLTcN6XpA/tq1qypgICANHsy+OnTp1W6dGnduHGDJ4MDSBNLlizhyeAAgAzlnXfeSfRY1rIs7d+/X5Iy/pPBpduXUZUvX17ly5e3323lXvLmzetwK9o75cyZ0+EWtnc+qfd+82XPnv2eZyGyZs3qcAvbpI4D8HjJnTv3Pc/O5suXT99++63DsEKFCj2MsgAAuKfEjmUjIyPl6uqq0qVLP5T+LGn2ZHAAAAAAjy+CBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaKeTp6SlXV1d5eno6uxQAhvC9frzweQPIiDLStiuTswvIqPLnz6/58+crZ86czi4FgCF8rx8vfN4AMqKMtO3ijEYqZIQPGEDy8L1+vPB5A8iIMsq2i6ABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwLhMzi4ASI74mHBnl5Bi8dHhDv9N8nwZ+D0DSF9MbU9Suj0D23Q8XggayBC8vLzk7uGhqHPbnV1KqkX9k/z34O7hIS8vrzSoBsDjIK22oSnZnoFtOh4fBA1kCD4+Ppr5+ecKD3+0fwmKiorS8ePH9eSTTypLliz24V5eXvLx8XFiZQAysvSyDb3XNu5xwzYdjwuCBjIMHx+fR37DHBkZqejoaD311FPKli2bs8sB8AhJD9tQtnHA44XO4AAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIwjaAAAAAAwjqABAAAAwDiCBgAAAADjCBoAAAAAjCNoAAAAADDOxbIs60ET/fHHH7IsSx4eHg+jpiSxLEuxsbFyd3eXi4uLs8t5pNHWDw9t/XBlhPaOiYmRi4uLKleu7OxS0p30sm/KCOtRekFbJR1tlXS0VdKZaquk7psyJWVh6fFDc3FxcfrO5XFBWz88tPXDlRHa28XFJV1ug9OD9NIuGWE9Si9oq6SjrZKOtko6U22V1H1Tks5oAAAAAEBy0EcDAAAAgHEEDQAAAADGETQAAAAAGEfQAAAAAGAcQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgXIYPGnFxcfryyy/VpUsXBQQEqFq1aurWrZt+//13Z5f2SNq6datef/11NWjQQH5+fvrwww+dXdIj4+jRo3rppZdUqVIl1apVS59++qliYmKcXdYj6eTJk3rvvffUsmVLlSlTRs8//7yzS0IG88svv+iFF15Q+fLl1bhxYy1btizJ8+7Zs0c9e/aUv7+/KleurPbt2+vgwYNpWK1zpaatbF5++WX5+flpzpw5aVBh+pGSttq7d69GjBihhg0bqmLFimrUqJEmTpyoyMjIh1Bx2kvpvtGyLH3xxReqW7euKlSooA4dOmjPnj1pX7ATpaStLly4oE8//VQtW7aUv7+/ateurddff11nz541UlOGDxpRUVH64osvVLZsWX3yySeaMGGCcubMqe7du2vbtm3OLu+Rs3nzZh06dEjPPPOMvLy8nF3OI+PatWvq0aOHYmNjNXXqVL322mtaunSpxo0b5+zSHklHjhzRxo0bVaxYMZUoUcLZ5SCD+f333zV48GBVqlRJX375pZo2baq3335bP//88wPn3bZtm7p166bixYtr2rRpmjRpkp599lndvHnzIVT+8KWmrWw2btyoP//8Mw2rTB9S2larV6/WyZMn1adPH33xxRfq0aOHli5dqgEDBjykytNOavaNX375paZMmaKePXtq1qxZyps3r3r16qXTp08/hMofvpS21f79+7Vu3To1bdpUM2bMUFBQkA4fPqx27drp8uXLqS/MyuBu3bplXb16NcGwJk2aWP3793dSVY+uuLg4+//Xq1fP+uCDD5xYzaNj5syZVqVKlawrV67Yh/33v/+1SpcubZ0/f955hT2i7lyP33rrLat58+ZOrAYZTa9evawOHTo4DBs2bJjVtGnT+84XGxtr1atXz/r000/Tsrx0JaVtZRMdHW01bNjQ+u677yxfX19r9uzZaVFmupDStrp06VKCYT/++KPl6+tr7du3z2iND1tK941RUVFW5cqVrYkTJ9qHRUdHW/Xq1bPef//9NKzYeVLaVteuXbNiY2Mdhv3zzz+Wn5+fNWfOnFTXleHPaLi5uSlnzpwJhvn5+enChQtOqurR5eqa4VeZdGnTpk2qUaOGcuXKZR/WtGlTxcfHa+vWrc4r7BHFeoyUiomJUWhoqJo0aeIwvFmzZjp69KjOnDlzz3lDQkJ09uxZde/ePa3LTBdS01Y2c+bMkZeXl9q0aZNWZaYLqWkrb2/vBMPKlCkjSRn+OCil+8Y//vhD169fV9OmTe3DPDw81LBhQ23atCktS3aalLaVl5eXMmXK5DAsf/788vb2NrL+PJJ721u3bunPP//UU0895exSgCQ5duxYgvXVy8tLefPm1bFjx5xUFYC7nTp1SrGxsQm+r7ZL8O73ff3zzz+VK1cu7du3T40bN1aZMmXUuHFjrVixIi1LdprUtJUknTt3Tl988YXeeecdubi4pFmd6UFq2+puu3btkqQMfxyU0n2jbVxi7Xnu3DlFRUWZL9bJTB5HHD9+XJcuXTJyafEjGTRmz56tsLAw9ezZ09mlAEkSHh6eaJ+XnDlz6tq1a06oCEBibN/Hu7+vtr/v9339999/dfPmTY0cOVLdunXTnDlzVLVqVb311lvavHlz2hXtJKlpK0n6+OOP1bBhQ1WqVClN6ktPUttWd7p8+bKmTp2q5557TsWLFzdWozOkdN8YHh4uDw8PZc6c2WG4l5eXLMt6JPerpo4jLMvS6NGj5ePjo+bNm6e6rkwPnuThi4iISNLpmiJFisjDw8Nh2NatWzV16lS9/PLLKleuXFqV+MhITVsDwKMgOdvB1LAsS9HR0XrjjTfUtWtXSVKNGjV07NgxzZw5U88++2yqlv8wPKy22rJli7Zs2ZKsTuPpzcNqqzvFxsZq2LBhkqRRo0YZWy4eH1OnTtX27ds1e/ZsZcuWLdXLS5dB4+eff9Y777zzwOl++uknh9M6+/fv15AhQ/T8889r8ODBaVniIyOlbQ2zvLy8FBERkWD4tWvXEvRBAmBWcraDtu/j3d/X8PBwSbrv99X2a2P16tUdhteoUUOLFi1KVs3O8rDaavTo0erevbuyZs1qn16SoqOj7/nLbXrzsNrKxrIsjRw5Unv37tXixYvl4+OTgqrTl5TuG728vBQTE6Po6GiHsxrh4eFycXF5JPerJo4jli5dqunTp2vMmDGqUaOGkbrSZdBo166d2rVrl6x5Tp48qb59+8rf31+jR49Oo8oePSlpa5j31FNPJbiGMiIiQv/++2+Gv8YWSO+Ssx2MiYmRu7u7jh075nAG4l7XhN/p6aefvue46OjoJFbrXA+rrY4fP66ZM2dq5syZDsMnT56syZMna+/evQkui0lvHlZb2XzyySdavXq1vvzyS5UqVSplRaczKd032sYdP37coS2OHTumggULKkuWLGlTsBOl9jhi3bp1GjVqlIYOHaq2bdsaq+uR6KNx4cIF9erVSwUKFNCUKVPk7u7u7JKAZKldu7ZCQkIcfrn7+eef5erqqlq1ajmxMgB38vDwUEBAgNasWeMw3HbWt3DhwvecNzAwUO7u7goJCXEYHhISorJly6ZJvc6UmraaP39+gn+S1LFjR82fP/+R28+npq0k6YsvvtDXX3+tcePGGfslOj1I6b6xcuXK8vT01OrVq+3DYmNjtXbtWtWuXTtNa3aW1BxHhIaGatiwYWrXrp0GDRpktK50eUYjOaKiotS3b19duXJFb7/9to4cOWIf5+HhYb/FG8w4e/as9u3bJ0m6efOmTp06Zb+G9u7b8iHpOnbsqAULFmjQoEHq37+/wsLC9Omnn6pjx47Kly+fs8t75Ny8eVMbN26UdHudvn79un09rlatWqK3iwRsBg4cqO7du2vUqFFq2rSpQkNDtXLlSk2aNMlhujJlyqhVq1YaO3asJClPnjzq1q2bJk+eLBcXF5UoUUKrVq3Snj17NHv2bGe8lTSX0rYKCAhIdHlFixa957iMLqVtFRwcrIkTJ+qFF15Q4cKFHZ5+XbRo0Qy9PUvqvrFHjx46d+6c1q1bJ0nKnDmz+vfvr6lTp8rb21u+vr765ptvdPXqVfXu3dtZbydNpbStjh49qkGDBql48eJq2bKlw/rj7e2tokWLpqquDB80Ll68qEOHDkm6/SW9U6FChfTLL784o6xHVmhoqEaMGGH/e/Pmzfa7pfzvf/9zVlkZXs6cOTVv3jx99NFHGjRokLJnz662bdvqtddec3Zpj6RLly7plVdecRhm+3v+/PmP7IEMzKhataqmTp2qzz77TN99950KFiyo0aNHO9yzX5Li4uIUHx/vMOz1119XtmzZNGfOHF2+fFklSpTQ9OnTFRgY+DDfwkOTmrZ63KS0rWzPSPjxxx/1448/Okz78ccfZ+hnkCR13xgfH6+4uDiHYX379pVlWfrqq690+fJllS5dWnPmzDHa+T49SWlb/fnnn4qIiFBERIQ6derkMG3r1q2T9BT2+3GxLMtK1RIAAAAA4C6PRB8NAAAAAOkLQQMAAACAcQQNAAAAAMYRNAAAAAAYR9AAAAAAYBxBAwAAAIBxBA0AAAAAxhE0AAAAABhH0AAAAABgHEEDGdKiRYvk5+endu3aObsUAMBjavny5fLz80v034QJE5xdHuB0mZxdAJASwcHBKlSokPbu3auTJ0+qWLFizi4JAPCYGjp0qAoXLuwwzNfX10nVAOkHQQMZzunTp7V7925NmzZN7733noKDgzV48GBnlwUAeEzVrl1b5cuXN7a8yMhIZcuWzdjyAGfh0ilkOMHBwcqZM6fq1Kmjxo0bKzg4OME0V65c0fDhw1W5cmVVrVpVb731lg4dOiQ/Pz8tX77cYdqjR49q6NChqlatmsqXL682bdpow4YND+vtAAAeQWfPntWoUaPUuHFjVahQQQEBARo6dKjOnDnjMJ3t8qsdO3Zo1KhRqlGjhurUqWMfv3HjRnXu3FmVKlWSv7+/+vXrpyNHjjzstwOkCGc0kOEEBwerYcOG8vDw0PPPP69vvvlGe/fuVYUKFSRJ8fHxGjhwoPbu3atOnTrpqaee0oYNG/TWW28lWNaRI0fUqVMn5cuXT3379lW2bNm0evVqDRo0SFOnTlXDhg0f9tsDAGQw169f1+XLlx2G7du3T7t371bz5s2VP39+nT17Vt988426d++uVatWKWvWrA7Tf/DBB/L29tagQYMUGRkpSVqxYoWCgoIUGBioN954Qzdv3tQ333yjzp076/vvv09wuRaQ3hA0kKH89ddfOnbsmN59911JUpUqVZQ/f34FBwfbg8b69eu1e/dujRw5Uj169JAkderUSS+99FKC5Y0ZM0YFChTQsmXL5OHhIUnq3LmzOnXqpAkTJhA0AAAP1LNnzwTD/vzzTzVp0sRhWL169dShQwetWbNGrVq1chiXM2dOff3113Jzc5Mk3bhxQ2PGjFG7du300Ucf2adr3bq1mjRpolmzZjkMB9IjggYylODgYOXJk0cBAQGSJBcXFzVr1kw//vijgoKC5Obmps2bN8vd3V3t27e3z+fq6qouXbpo+/bt9mFXr17V9u3bNXToUF2/ft3hdQIDAzV16lSFhYUpX758D+fNAQAypPfee09PPvmkw7AsWbLY/z82NlbXr19X0aJF5eXlpQMHDiQIGu3bt7eHDEkKCQlReHi4mjdv7nC2xNXVVRUrVlRoaGjavBnAIIIGMoy4uDitWrVKAQEBDte4VqhQQV999ZW2bdumwMBAnTt3Tnnz5k1wWrpo0aIOf586dUqWZWny5MmaPHlyoq956dIlggYA4L4qVKiQoDN4VFSUZs2apeXLlyssLEyWZdnHRUREJFjG3ZdBnThxQpLsZ+bv5unpmcqqgbRH0ECGsX37dv37779atWqVVq1alWB8cHCwAgMDk7y8+Ph4SVKvXr307LPPJjrN3eEEAICk+Oijj7R8+XL16NFDlSpVUo4cOeTi4qLXXnvNIXTYZM6c2eFv2zSffvqp8ubNm2D6O89+AOkVQQMZRnBwsJ544gm99957CcatW7dO69at0wcffKCCBQsqNDRUN2/edDircerUKYd5ihQpIklyd3dXzZo107Z4AMBjxdYPIygoyD4sOjo60bMZibHto5544gn2UciwuL0tMoSoqCitXbtWdevWVZMmTRL869Kli27cuKFffvlFgYGBio2N1dKlS+3zx8fHa9GiRQ7LfOKJJ1StWjUtWbJEFy5cSPCad99BBACApErsjMOCBQsUFxeXpPmfffZZeXp6atasWYqNjU0wnn0UMgLOaCBD+OWXX3Tjxg3Vr18/0fGVKlWSt7e3fvzxR02fPl0VKlTQJ598olOnTumpp57SL7/8omvXrkm63YHc5v3331fnzp3VokULtW/fXkWKFNHFixe1Z88enT9/Xj/++ONDeX8AgEdL3bp19cMPP8jT01MlS5bUnj17FBISoly5ciVpfk9PT40aNUpvvvmm2rRpo2bNmsnb21vnzp3Txo0bVbly5UTP8APpCUEDGcKPP/6ozJkzq1atWomOd3V1Vd26dRUcHKzw8HDNmjVLY8aM0ffffy9XV1c1bNhQgwYNUqdOnRyugy1ZsqSWLVumadOm6fvvv9fVq1fl7e2tMmXKaNCgQQ/r7QEAHjFvv/22XF1dFRwcrOjoaFWuXFlz585Vnz59kryMFi1ayMfHR1988YXmzJmjmJgY5cuXT1WrVlWbNm3SsHrADBcrsR5JwCNo/fr1GjRokBYvXqwqVao4uxwAAIBHGn008EiKiopy+DsuLk4LFiyQp6enypYt66SqAAAAHh9cOoVH0kcffaSoqCj5+/srJiZGa9eu1e7duzVs2DCHhygBAAAgbXDpFB5JwcHBmjt3rk6ePKno6GgVK1ZMnTp1UteuXZ1dGgAAwGOBoAEAAADAOPpoAAAAADCOoAEAAADAOIIGAAAAAOMIGgAAAACMI2gAAAAAMI6gAQAAAMA4ggYAAAAA4wgaAAAAAIz7P0BhbSaE98tCAAAAAElFTkSuQmCC\n"
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Shape of the dataframe before outlier removal: (657, 8)\n",
            "Outlier detection upper bound for Fare: 0.17\n",
            "Outlier detection lower bound for Fare: -0.89\n",
            "Shape of the dataframe after removing Fare outliers: (653, 8)\n",
            "Outlier detection upper bound for Age: 1.09\n",
            "Outlier detection lower bound for Age: -1.68\n",
            "Shape of the dataframe after removing Fare outliers: (588, 8)\n",
            "69 rows removed as outliers.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "5XuJD3u8RWZ9"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}